openapi: 3.0.3
info:
  description: 'You can use Spotify''s Web API to discover music and podcasts, manage
    your Spotify library, control audio playback, and much more. Browse our available
    Web API endpoints using the sidebar at left, or via the navigation bar on top
    of this page on smaller screens.


    In order to make successful Web API requests your app will need a valid access
    token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth
    2.0</a>.


    The base URI for all Web API requests is `https://api.spotify.com/v1`.


    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web
    API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify
    for Developers community forum</a> to ask questions and connect with other developers.

    '
  version: 2025.5.18
  title: Spotify Web API with fixes and improvements from sonallux
  termsOfService: https://developer.spotify.com/terms/
  contact:
    name: sonallux
    url: https://github.com/sonallux/spotify-web-api
servers:
- url: https://api.spotify.com/v1
tags:
- name: Albums
- name: Artists
- name: Audiobooks
- name: Categories
- name: Chapters
- name: Episodes
- name: Library
- name: Genres
- name: Markets
- name: Player
- name: Playlists
- name: Search
- name: Shows
- name: Tracks
- name: Users
paths:
  /albums/{id}:
    get:
      operationId: get-an-album
      tags:
      - Albums
      summary: 'Get Album

        '
      description: 'Get Spotify catalog information for a single album.

        '
      security:
      - oauth_2_0: []
  /albums/{id}/tracks:
    get:
      operationId: get-an-albums-tracks
      tags:
      - Albums
      - Tracks
      summary: 'Get Album Tracks

        '
      description: 'Get Spotify catalog information about an album’s tracks.

        Optional parameters can be used to limit the number of tracks returned.

        '
      security:
      - oauth_2_0: []
  /artists/{id}:
    get:
      tags:
      - Artists
      operationId: get-an-artist
      summary: 'Get Artist

        '
      description: 'Get Spotify catalog information for a single artist identified
        by their unique Spotify ID.

        '
      security:
      - oauth_2_0: []
  /artists/{id}/albums:
    get:
      tags:
      - Artists
      - Albums
      operationId: get-an-artists-albums
      summary: 'Get Artist''s Albums

        '
      description: 'Get Spotify catalog information about an artist''s albums.

        '
      security:
      - oauth_2_0: []
  /artists/{id}/top-tracks:
    get:
      deprecated: true
      tags:
      - Artists
      - Tracks
      operationId: get-an-artists-top-tracks
      summary: 'Get Artist''s Top Tracks

        '
      description: 'Get Spotify catalog information about an artist''s top tracks
        by country.

        '
      security:
      - oauth_2_0: []
  /search:
    get:
      tags:
      - Search
      operationId: search
      summary: 'Search for Item

        '
      description: 'Get Spotify catalog information about albums, artists, playlists,
        tracks, shows, episodes or audiobooks

        that match a keyword string. Audiobooks are only available within the US,
        UK, Canada, Ireland, New Zealand and Australia markets.

        '
      security:
      - oauth_2_0: []
  /me:
    get:
      tags:
      - Users
      operationId: get-current-users-profile
      summary: 'Get Current User''s Profile

        '
      description: 'Get detailed profile information about the current user (including
        the

        current user''s username).

        '
      security:
      - oauth_2_0:
        - user-read-private
        - user-read-email
  /playlists/{playlist_id}:
    get:
      tags:
      - Playlists
      operationId: get-playlist
      summary: 'Get Playlist

        '
      description: 'Get a playlist owned by a Spotify user.

        '
      security:
      - oauth_2_0: []
  /playlists/{playlist_id}/items:
    get:
      tags:
      - Playlists
      - Tracks
      operationId: get-playlists-items
      summary: 'Get Playlist Items

        '
      description: 'Get full details of the items of a playlist owned by a Spotify
        user.


        **Note**: This endpoint is only accessible for playlists owned by the current
        user or playlists the user is a collaborator of. A `403 Forbidden` status
        code will be returned if the user is neither the owner nor a collaborator
        of the playlist.

        '
      security:
      - oauth_2_0:
        - playlist-read-private
    put:
      tags:
      - Playlists
      - Tracks
      operationId: reorder-or-replace-playlists-items
      summary: 'Update Playlist Items

        '
      description: 'Either reorder or replace items in a playlist depending on the
        request''s parameters.

        To reorder items, include `range_start`, `insert_before`, `range_length` and
        `snapshot_id` in the request''s body.

        To replace items, include `uris` as either a query parameter or in the request''s
        body.

        Replacing items in a playlist will overwrite its existing items. This operation
        can be used for replacing or clearing items in a playlist.

        <br/>

        **Note**: Replace and reorder are mutually exclusive operations which share
        the same endpoint, but have different parameters.

        These operations can''t be applied together in a single request.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    post:
      tags:
      - Playlists
      - Tracks
      operationId: add-items-to-playlist
      summary: 'Add Items to Playlist'
      description: 'Add one or more items to a user''s playlist.'
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /me/playlists:
    get:
      tags:
      - Playlists
      - Library
      operationId: get-a-list-of-current-users-playlists
      summary: 'Get Current User''s Playlists

        '
      description: 'Get a list of the playlists owned or followed by the current Spotify

        user.

        '
      security:
      - oauth_2_0:
        - playlist-read-private
    post:
      tags:
      - Playlists
      - Library
      operationId: create-playlist
      summary: 'Create Playlist'
      description: 'Create a playlist for the current Spotify user. (The playlist will be empty until you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)Each user is generally limited to a maximum of 11000 playlists.'
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /playlists/{playlist_id}/images:
    get:
      tags:
      - Playlists
      operationId: get-playlist-cover
      summary: 'Get Playlist Cover Image

        '
      description: 'Get the current image associated with a specific playlist.

        '
      security:
      - oauth_2_0: []
  /browse/new-releases:
    get:
      deprecated: true
      tags:
      - Albums
      operationId: get-new-releases
      summary: 'Get New Releases

        '
      description: 'Get a list of new album releases featured in Spotify (shown, for
        example, on a Spotify player’s “Browse” tab).

        '
      security:
      - oauth_2_0: []
components:
  securitySchemes:
    oauth_2_0:
      type: oauth2
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            app-remote-control: 'Communicate with the Spotify app on your device.

              '
            playlist-read-private: 'Access your private playlists.

              '
            playlist-read-collaborative: 'Access your collaborative playlists.

              '
            playlist-modify-public: 'Manage your public playlists.

              '
            playlist-modify-private: 'Manage your private playlists.

              '
            user-library-read: 'Access your saved content.

              '
            user-library-modify: 'Manage your saved content.

              '
            user-read-private: 'Access your subscription details.

              '
            user-read-email: 'Get your real email address.

              '
            user-follow-read: 'Access your followers and who you are following.

              '
            user-follow-modify: 'Manage your saved content.

              '
            user-top-read: 'Read your top artists and content.

              '
            user-read-playback-position: 'Read your position in content you have played.

              '
            user-read-playback-state: 'Read your currently playing content and Spotify
              Connect devices information.

              '
            user-read-recently-played: 'Access your recently played items.

              '
            user-read-currently-playing: 'Read your currently playing content.

              '
            user-modify-playback-state: 'Control playback on your Spotify clients
              and Spotify Connect devices.

              '
            ugc-image-upload: 'Upload images to Spotify on your behalf.

              '
            streaming: 'Play content and control playback on your other devices.

              '
